In [1]:
import numpy as np

a = np.array([1,2,3])

In [2]:
a

array([1, 2, 3])

In [3]:
print(a)

[1 2 3]


In [4]:
type(a)

numpy.ndarray

In [5]:
a.sum()

6

In [7]:
a.shape

(3,)

In [9]:
b = np.array([[1,2,3],[4,5,6]])

In [10]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b.shape

(2, 3)

In [12]:
c = np.array([2,4,5,8,10,12])

In [13]:
c1 = c.reshape(2,3)
c1

array([[ 2,  4,  5],
       [ 8, 10, 12]])

In [15]:
# ２次元の参照を返す（メモリが一つでよい）
c2 = c1.ravel()
c2

array([ 2,  4,  5,  8, 10, 12])

In [16]:
# 2次元のコピーを返す（メモリが２重で食う）
c3 = c1.flatten()
c3

array([ 2,  4,  5,  8, 10, 12])

In [17]:
# データ型
a.dtype

dtype('int32')

In [18]:
d = np.array([1,2], dtype=np.int64)
d

array([1, 2], dtype=int64)

In [19]:
d.dtype

dtype('int64')

In [20]:
# 途中で型変換
d1 = d.astype(np.float16)
d1

array([1., 2.], dtype=float16)

In [22]:
# インデックスとスライス
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [24]:
a[0]

1

In [25]:
a[-1]

6

In [27]:
a[1:]

array([2, 3, 4, 5, 6])

In [28]:
a[:]

array([1, 2, 3, 4, 5, 6])

In [29]:
b = np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
b[0]

array([1, 2, 3, 4])

In [31]:
b[0,1]

2

In [32]:
b[1,0]

5

In [33]:
b[:, 2]

array([3, 7])

In [34]:
b[0, 1:]

array([2, 3, 4])

In [35]:
a = np.array([1,2,3,4]) 
a[0] = 10
a

array([10,  2,  3,  4])

In [37]:
a = 0
a

0

In [38]:
a

0

In [39]:
b = np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
b[1,2] = 10
b

array([[ 1,  2,  3,  4],
       [ 5,  6, 10,  8]])

In [44]:
b[0, :] = 0
b

array([[0, 0, 0, 0],
       [5, 6, 0, 8]])

In [52]:
# 乱数の発生(float)
np.random.seed(1)
np.random.random((5,5))

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01],
       [9.23385948e-02, 1.86260211e-01, 3.45560727e-01, 3.96767474e-01,
        5.38816734e-01],
       [4.19194514e-01, 6.85219500e-01, 2.04452250e-01, 8.78117436e-01,
        2.73875932e-02],
       [6.70467510e-01, 4.17304802e-01, 5.58689828e-01, 1.40386939e-01,
        1.98101489e-01],
       [8.00744569e-01, 9.68261576e-01, 3.13424178e-01, 6.92322616e-01,
        8.76389152e-01]])

In [60]:
# 乱数の発生(int)
np.random.seed(1)
np.random.randint(1,10)

4

In [65]:
# 数列を返す
np.arange(10)
np.arange(2,11)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
x = np.arange(5)
y = np.arange(3)
xx, yy = np.meshgrid(x, y)

# x,yの全ての組み合わせ
for vx, vy in zip(xx, yy):
    for px, py in zip(vx, vy):
        print("[{}, {}]".format(px, py))

[0, 0]
[1, 0]
[2, 0]
[3, 0]
[4, 0]
[0, 1]
[1, 1]
[2, 1]
[3, 1]
[4, 1]
[0, 2]
[1, 2]
[2, 2]
[3, 2]
[4, 2]


In [81]:
# 全てが0の配列
np.zeros((3,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [82]:
# 全てが1の配列
np.ones(3)

array([1., 1., 1.])

In [83]:
# 特定の値の配列を生成する
np.full(3,10)

array([10, 10, 10])

In [84]:
np.full((2,3), 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [85]:
# 均等に分割したデータを生成する(0～1を５等分)
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [88]:
# 配列の連結
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])
np.concatenate([a1, a2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [93]:
# ２次元配列の連結(参照)
b1 = np.array([[1,2,3,4],[5,6,7,8]])
b2 = np.array([[5,6,7,8],[10,11,12,13]])
np.concatenate([b1, b2], axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [95]:
# ２次元配列の連結(コピー)
b1 = np.array([[1,2,3,4],[5,6,7,8]])
b2 = np.array([[5,6,7,8],[10,11,12,13]])
np.hstack([b1, b2])

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 5,  6,  7,  8, 10, 11, 12, 13]])

In [96]:
# ２次元配列の連結(コピー)
b1 = np.array([[1,2,3,4],[5,6,7,8]])
b2 = np.array([[5,6,7,8],[10,11,12,13]])
np.vstack([b1, b2])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [101]:
# 2分割
h = np.array([[1,2,3,4],[5,6,7,8]])
h1, h2 = np.hsplit(h, [3])
# print(h1)
# print(h2)

# 3分割
h1, h2, h3 = np.hsplit(h, [2,3])
print(h1)
print(h2)
print(h3)

[[1 2]
 [5 6]]
[[3]
 [7]]
[[4]
 [8]]


In [105]:
# 2分割
v = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v1, v2 = np.vsplit(v, [3])
# print(v1)
# print(v2)

# 3分割
v = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v1, v2, v3 = np.vsplit(v, [1,3])
print(v1)
print(v2)
print(v3)

[[1 2 3]]
[[4 5 6]
 [7 8 9]]
[[10 11 12]]


In [106]:
# 配列の転置
v = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [108]:
# ユニバーサルファンクション
a = np.array([-1, 2, 3, -5])
# 絶対値
np.abs(a)

array([1, 2, 3, 5])

In [113]:
# ユニバーサルファンクション
a = np.array([0.0, np.pi / 4.0, np.pi / 2.0])
# sin
np.sin(a)

array([0.        , 0.70710678, 1.        ])

In [114]:
# ブロードキャスト（全ての要素に演算処理を行う）
a = np.array([1,2,3,4,5])
print(a + 10)
print(a - 10)
print(2 * a)
print(a / 2)

[11 12 13 14 15]
[-9 -8 -7 -6 -5]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [115]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [117]:
# 論理値判定
a = np.array([1, 2, -1, -5, 10])
# 各要素が０より大きいか
np.array(a > 0)

3

In [118]:
# 配列で0ではない要素をカウント
np.count_nonzero(a > 0)

3

In [119]:
# 配列の合計要素のカウント
np.sum(a > 0)

3

In [120]:
# 要素の中に(１つでも)Trueが含まれているかどうかを調べる
np.any(a > 0)

True

In [122]:
# 要素の中に全てTrueであるかどうかを調べる
np.all(a > 0)

False

In [123]:
# 0より大きく要素を取り出す
a[a > 0]

array([ 1,  2, 10])

In [126]:
a = np.array([1,2,3,4])
b = np.array([1,3,3,4])
c = np.array([1,2,3,4])
a == b

array([ True, False,  True,  True])

In [127]:
# 全く同じ場合、Trueを返す、それ以外はFalseを返す
print(np.allclose(a, b))
print(np.allclose(a, c))

False
True
